Consolidate waiting for connection logic, use Python.
google-ml-infra/actions pull request #2
Opened 2024-09-24 18:52 UTC by belitskiy

Also, polish the code a bit, use API to retrieve PR labels.

2024-09-24 18:54 UTC, belitskiy commented
Oops, not sure how that lame amend made it in there... Oh, I ran `git commit -am --amend --no-edit` 🤣

2024-09-25 16:44 UTC, MichaelHudgins requested changes

2024-09-25 16:51 UTC, belitskiy commented on ci_connection/wait_for_connection.py
> +  always_halt_label = "CI Connection Halt - Always"
`CI` instead of `ML` seems better to me - it's a bit clearer what it's for, IMO.
Perhaps:
`Workflow Connect...`
`Action Connect...`

2024-09-25 16:55 UTC, belitskiy commented on ci_connection/wait_for_connection.py
> +  always_halt_label = "CI Connection Halt - Always"
This is probably way over the top, but perhaps labels could be stored as a config somewhere, and a workflow could be run on updating that file, to update the labels (API allows this) for the repo

2024-09-25 18:03 UTC, MichaelHudgins commented on ci_connection/wait_for_connection.py
> +  always_halt_label = "CI Connection Halt - Always"
Hmm yeah probably over the top for now, for this probably pull as constants at the top and lets iterate on naming separately after landing

2024-09-25 18:38 UTC, belitskiy commented on ci_connection/wait_for_connection.py
> +  always_halt_label = "CI Connection Halt - Always"
Done

2024-09-26 18:02 UTC, MichaelHudgins approved these changes

2024-09-27 17:28 UTC, merged